services:
  - type: web
    name: automarketplace-v5
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile

    healthCheckPath: /api/public/vehicles

    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: automarketplace-db
          property: connectionString

      - key: APP_JWT_SECRET
        generateValue: true

databases:
  - name: automarketplace-db
    plan: free
    databaseName: automarketplace
    user: automarketplace
