server:
  port: ${PORT:8080}
  forward-headers-strategy: framework

spring:

  sql:
    init:
      mode: always
      continue-on-error: false

  jpa:
    open-in-view: false

    hibernate:
      ddl-auto: update

    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  jackson:
    serialization:
      write-dates-as-timestamps: false

app:
  jwt-secret: ${APP_JWT_SECRET:AutoMarketplace-V1-Secret-Key-Change-This-In-Production-2026}
