spring:

  sql:
    init:
      mode: always

  jpa:
    hibernate:
      ddl-auto: update

    open-in-view: false

    properties:
      hibernate:
        format_sql: true

app:
  jwt-secret: ${APP_JWT_SECRET:AutoMarketplace-V1-Secret-Key-Change-This-In-Production-2026}
